### ISSUE TITLE
Can you add a license to the project?

### ISSUE THREAD

**Issue by exts** [starchphp/starch#1]
I like your framework, but I want to fork it to use my own [container](http://github.com/exts/Canister), or maybe I could create a PR which factors out the buildContainer method to make it more flexible?

I'll do that now if you wish.

**Comment by Brammm** [comment]
Yeah, I've been thinking of doing the same. What container are you thinking of using?

**Comment by exts** [comment]
The one I wrote above, it's psr-11 compliant.

**Comment by Brammm** [comment]
I didn't see the link on mobile @exts. 

Do you think the following would suite your needs: 

```
class App {
    public function __construct(ContainerInterface $container = null)
    {
        $this->buildContainer($container);
    }

    private function buildContainer() : void
    {
        $builder = new ContainerBuilder();

        if (null !== $container) {
            $builder->wrapContainer($container);
        }

        $builder->addDefinitions([
            EmitterInterface::class => object(SapiEmitter::class),

            InvokerInterface::class => get(Container::class),

            StackInterface::class => object(Stack::class),
        ]);

        $this->configureContainer($builder);

        $this->container = $builder->build();
    }
}
```

I haven't used the wrap functionality myself so far, but as far as I understand, that should do it.

**Comment by exts** [comment]
I just made a cleaner PR [here](https://github.com/starchphp/starch/pull/2) with a similar idea.

**Comment by Brammm** [comment]
@exts Concerning license, it's defined in the composer.json: LGPL-3.0+. So feel free to fork if you want. I have some ideas though, will work on them today.

**Comment by Brammm** [comment]
License was changed to MIT.
