### ISSUE TITLE
Is it possible to push 0.3?

### ISSUE THREAD

**Issue by exts** [starchphp/starch#6]
I don't want to be on dev-master and I just solved a pretty big issue that you solved w/ the way routing works (you might've seen my other thread). Had to update my code to work with master and all is well.

**Comment by Brammm** [comment]
I'm so sorry I didn't see this. I'm assuming it was you who reached out on Twitter? In any case. latest code has been tagged.

**Comment by exts** [comment]
Yeah that was me, I had to do an emergency update to my invoice system and the changes you made fixed a lot of issues I ran into. Didn't feel comfortable on master, but had to risks it for the client.
